apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-frontend
spec:
  {{ if .Values.frontend.ingress }}
  type: NodePort
  {{ else }}
  type: LoadBalancer
  {{ end }}
  selector:
    app: {{ .Release.Name }}-frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.port }}
      targetPort: 80