# .github/workflows/pr-cleanup.yml
name: PRCleanup
on:  ['deployment']
 

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        release: 'nginx'
        namespace: 'default'
        chart: 'chartmuseum/app'
        token: '${{ github.token }}'
  
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
