# .github/workflows/deploy.yml
name: Deploy
on: 
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'helm install '
      run: 
        apt-get update
        sudo apt-get install -y curl
        sudo apt-get install wget
        wget https://get.helm.sh/helm-v3.9.2-linux-amd64.tar.gz
        tar -zxvf helm-v3.9.2-linux-amd64.tar.gz
        mv linux-amd64/helm /usr/local/bin/helm
    - name: 'Create helm Chart'
      run:   
         helm create helloworld
         tree helloworld  
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
