# .github/workflows/deploy.yml
name: Deploy
on: 
  push:
  workflow_dispatch:

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'helm install '
      run: 
        apt-get update
        sudo apt-get install -y curl
        curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
        sudo apt-get install apt-transport-https --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
        sudo apt-get update
        sudo apt-get install helm
    - name: 'Create helm Chart'
      run:   
         helm create helloworld
         tree helloworld  
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
